### ISSUE TITLE
Transfer component assets

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-build#150]
We should include assets in the components build process.

**Comment by jurekbarth** [comment]
Just images or do you expect some kind of special pattern for copying stuff?

**Comment by timomayer** [comment]
like that to bundle assets with components, downside is that we habve a lot of duplicated assets (like dummy images) in each component.
@jurekbarth when we are doing it we should consider anything. (images, videos, ...)

**Comment by SheepFromHeaven** [comment]
@jurekbarth are you still working on that?

**Comment by jurekbarth** [comment]
@SheepFromHeaven it works now for the loaders with webpack, so i think we're on a good way. Please reopen if you need any additional stuff 👍

**Comment by smohadjer** [comment]
@jurekbarth I would like to keep my component's assets with my component where other component resources are. Right now if I do so, when I run gulp serve assets can be reached, but when gulp build runs assets aren't available anymore. Can we have this fixed?

**Comment by jurekbarth** [comment]
@smohadjer right now it only works if you import in typescript files. So would a `data` directory inside your component folder solve your needs? Because we implemented that here #193

**Comment by smohadjer** [comment]
Typescript is here irrelevant because a component may not have any scripts to start with and still have assets. I guess we can use data folder for this purpose, though it's not really then consistent with global folder structure.
